[project]
name = "h24c3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "importlib>=1.0.4",
    "matplotlib>=3.9.2",
    "streamlit>=1.40.2",
]
